// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unscriptable.Infrastructure.Data;

#nullable disable

namespace Unscriptable.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430090111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentGroup", b =>
                {
                    b.Property<int>("Groupsid")
                        .HasColumnType("integer")
                        .HasColumnName("groupsid");

                    b.Property<int>("Studentsid")
                        .HasColumnType("integer")
                        .HasColumnName("studentsid");

                    b.HasKey("Groupsid", "Studentsid")
                        .HasName("pk_student_groups");

                    b.HasIndex(new[] { "Studentsid" }, "ix_student_groups_studentsid");

                    b.ToTable("student_groups", (string)null);
                });

            modelBuilder.Entity("TestCourse", b =>
                {
                    b.Property<int>("Coursesid")
                        .HasColumnType("integer")
                        .HasColumnName("coursesid");

                    b.Property<int>("Testsid")
                        .HasColumnType("integer")
                        .HasColumnName("testsid");

                    b.HasKey("Coursesid", "Testsid")
                        .HasName("pk_test_courses");

                    b.HasIndex(new[] { "Testsid" }, "ix_test_courses_testsid");

                    b.ToTable("test_courses", (string)null);
                });

            modelBuilder.Entity("TestDirection", b =>
                {
                    b.Property<int>("Directionsid")
                        .HasColumnType("integer")
                        .HasColumnName("directionsid");

                    b.Property<int>("Testsid")
                        .HasColumnType("integer")
                        .HasColumnName("testsid");

                    b.HasKey("Directionsid", "Testsid")
                        .HasName("pk_test_directions");

                    b.HasIndex(new[] { "Testsid" }, "ix_test_directions_testsid");

                    b.ToTable("test_directions", (string)null);
                });

            modelBuilder.Entity("TestGroup", b =>
                {
                    b.Property<int>("Groupsid")
                        .HasColumnType("integer")
                        .HasColumnName("groupsid");

                    b.Property<int>("Testsid")
                        .HasColumnType("integer")
                        .HasColumnName("testsid");

                    b.HasKey("Groupsid", "Testsid")
                        .HasName("pk_test_groups");

                    b.HasIndex(new[] { "Testsid" }, "ix_test_groups_testsid");

                    b.ToTable("test_groups", (string)null);
                });

            modelBuilder.Entity("TestProject", b =>
                {
                    b.Property<int>("Projectsid")
                        .HasColumnType("integer")
                        .HasColumnName("projectsid");

                    b.Property<int>("Testsid")
                        .HasColumnType("integer")
                        .HasColumnName("testsid");

                    b.HasKey("Projectsid", "Testsid")
                        .HasName("pk_test_projects");

                    b.HasIndex(new[] { "Testsid" }, "ix_test_projects_testsid");

                    b.ToTable("test_projects", (string)null);
                });

            modelBuilder.Entity("TestStudent", b =>
                {
                    b.Property<int>("Studentsid")
                        .HasColumnType("integer")
                        .HasColumnName("studentsid");

                    b.Property<int>("Testsid")
                        .HasColumnType("integer")
                        .HasColumnName("testsid");

                    b.HasKey("Studentsid", "Testsid")
                        .HasName("pk_test_students");

                    b.HasIndex(new[] { "Testsid" }, "ix_test_students_testsid");

                    b.ToTable("test_students", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Iscorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("iscorrect");

                    b.Property<int>("Questionid")
                        .HasColumnType("integer")
                        .HasColumnName("questionid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_answers");

                    b.HasIndex(new[] { "Questionid" }, "ix_answers_questionid");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Attempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime>("Startedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<DateTime?>("Submittedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submittedat");

                    b.Property<int>("Testid")
                        .HasColumnType("integer")
                        .HasColumnName("testid");

                    b.HasKey("Id")
                        .HasName("pk_attempts");

                    b.HasIndex(new[] { "Studentid" }, "ix_attempts_studentid");

                    b.HasIndex(new[] { "Testid" }, "ix_attempts_testid");

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_courses");

                    b.HasIndex(new[] { "Name" }, "ix_courses_name")
                        .IsUnique();

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_directions");

                    b.HasIndex(new[] { "Name" }, "ix_directions_name")
                        .IsUnique();

                    b.ToTable("directions", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Courseid")
                        .HasColumnType("integer")
                        .HasColumnName("courseid");

                    b.Property<int>("Directionid")
                        .HasColumnType("integer")
                        .HasColumnName("directionid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Projectid")
                        .HasColumnType("integer")
                        .HasColumnName("projectid");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex(new[] { "Courseid" }, "ix_groups_courseid");

                    b.HasIndex(new[] { "Directionid" }, "ix_groups_directionid");

                    b.HasIndex(new[] { "Name" }, "ix_groups_name")
                        .IsUnique();

                    b.HasIndex(new[] { "Projectid" }, "ix_groups_projectid");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex(new[] { "Name" }, "ix_projects_name")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answertype")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answertype");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("Isscoring")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isscoring");

                    b.Property<int?>("Maxscore")
                        .HasColumnType("integer")
                        .HasColumnName("maxscore");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("Testid")
                        .HasColumnType("integer")
                        .HasColumnName("testid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex(new[] { "Testid", "Number" }, "ix_questions_testid_number")
                        .IsUnique();

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Refreshtoken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Createdat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("Expiresat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat");

                    b.Property<DateTime?>("Revokedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revokedat");

                    b.Property<string>("Tokenhash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tokenhash");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_refreshtokens");

                    b.HasIndex(new[] { "Tokenhash" }, "ix_refreshtokens_tokenhash");

                    b.HasIndex(new[] { "Userid" }, "ix_refreshtokens_userid");

                    b.ToTable("refreshtokens", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatarpath")
                        .HasColumnType("text")
                        .HasColumnName("avatarpath");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("Vkprofilelink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vkprofilelink");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex(new[] { "Userid" }, "ix_students_userid")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Durationminutes")
                        .HasColumnType("integer")
                        .HasColumnName("durationminutes");

                    b.Property<bool>("Ispublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("ispublic");

                    b.Property<bool>("Isrepeatable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isrepeatable");

                    b.Property<int?>("Maxattempts")
                        .HasColumnType("integer")
                        .HasColumnName("maxattempts");

                    b.Property<int?>("Passingscore")
                        .HasColumnType("integer")
                        .HasColumnName("passingscore");

                    b.Property<DateTime>("Publishedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publishedat");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_tests");

                    b.ToTable("tests", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Testresult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attemptid")
                        .HasColumnType("integer")
                        .HasColumnName("attemptid");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<int>("Studentid")
                        .HasColumnType("integer")
                        .HasColumnName("studentid");

                    b.Property<int>("Testid")
                        .HasColumnType("integer")
                        .HasColumnName("testid");

                    b.HasKey("Id")
                        .HasName("pk_testresults");

                    b.HasIndex(new[] { "Attemptid" }, "ix_testresults_attemptid");

                    b.HasIndex(new[] { "Studentid" }, "ix_testresults_studentid");

                    b.HasIndex(new[] { "Testid", "Studentid", "Attemptid" }, "ix_testresults_testid_studentid_attemptid")
                        .IsUnique();

                    b.ToTable("testresults", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Middlename")
                        .HasColumnType("text")
                        .HasColumnName("middlename");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex(new[] { "Email" }, "ix_users_email")
                        .IsUnique();

                    b.HasIndex(new[] { "Login" }, "ix_users_login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Userattemptanswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attemptid")
                        .HasColumnType("integer")
                        .HasColumnName("attemptid");

                    b.Property<bool>("Iscorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("iscorrect");

                    b.Property<int>("Questionid")
                        .HasColumnType("integer")
                        .HasColumnName("questionid");

                    b.Property<int>("Scoreawarded")
                        .HasColumnType("integer")
                        .HasColumnName("scoreawarded");

                    b.HasKey("Id")
                        .HasName("pk_userattemptanswers");

                    b.HasIndex(new[] { "Attemptid", "Questionid" }, "ix_userattemptanswers_attemptid_questionid")
                        .IsUnique();

                    b.HasIndex(new[] { "Questionid" }, "ix_userattemptanswers_questionid");

                    b.ToTable("userattemptanswers", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Userselectedoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Answerid")
                        .HasColumnType("integer")
                        .HasColumnName("answerid");

                    b.Property<int>("Userattemptanswerid")
                        .HasColumnType("integer")
                        .HasColumnName("userattemptanswerid");

                    b.HasKey("Id")
                        .HasName("pk_userselectedoptions");

                    b.HasIndex(new[] { "Answerid" }, "ix_userselectedoptions_answerid");

                    b.HasIndex(new[] { "Userattemptanswerid" }, "ix_userselectedoptions_userattemptanswerid");

                    b.ToTable("userselectedoptions", (string)null);
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Usertextanswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Textanswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("textanswer");

                    b.Property<int>("Userattemptanswerid")
                        .HasColumnType("integer")
                        .HasColumnName("userattemptanswerid");

                    b.HasKey("Id")
                        .HasName("pk_usertextanswers");

                    b.HasIndex(new[] { "Userattemptanswerid" }, "ix_usertextanswers_userattemptanswerid")
                        .IsUnique();

                    b.ToTable("usertextanswers", (string)null);
                });

            modelBuilder.Entity("StudentGroup", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Group", null)
                        .WithMany()
                        .HasForeignKey("Groupsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_groups_groups_groupsid");

                    b.HasOne("Unscriptable.Domain.Entitties.Student", null)
                        .WithMany()
                        .HasForeignKey("Studentsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_groups_students_studentsid");
                });

            modelBuilder.Entity("TestCourse", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Course", null)
                        .WithMany()
                        .HasForeignKey("Coursesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_courses_courses_coursesid");

                    b.HasOne("Unscriptable.Domain.Entitties.Test", null)
                        .WithMany()
                        .HasForeignKey("Testsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_courses_tests_testsid");
                });

            modelBuilder.Entity("TestDirection", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Direction", null)
                        .WithMany()
                        .HasForeignKey("Directionsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_directions_directions_directionsid");

                    b.HasOne("Unscriptable.Domain.Entitties.Test", null)
                        .WithMany()
                        .HasForeignKey("Testsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_directions_tests_testsid");
                });

            modelBuilder.Entity("TestGroup", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Group", null)
                        .WithMany()
                        .HasForeignKey("Groupsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_groups_groups_groupsid");

                    b.HasOne("Unscriptable.Domain.Entitties.Test", null)
                        .WithMany()
                        .HasForeignKey("Testsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_groups_tests_testsid");
                });

            modelBuilder.Entity("TestProject", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Project", null)
                        .WithMany()
                        .HasForeignKey("Projectsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_projects_projects_projectsid");

                    b.HasOne("Unscriptable.Domain.Entitties.Test", null)
                        .WithMany()
                        .HasForeignKey("Testsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_projects_tests_testsid");
                });

            modelBuilder.Entity("TestStudent", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Student", null)
                        .WithMany()
                        .HasForeignKey("Studentsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_students_students_studentsid");

                    b.HasOne("Unscriptable.Domain.Entitties.Test", null)
                        .WithMany()
                        .HasForeignKey("Testsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_students_tests_testsid");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Answer", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("Questionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_questions_questionid");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Attempt", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Student", "Student")
                        .WithMany("Attempts")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempts_students_studentid");

                    b.HasOne("Unscriptable.Domain.Entitties.Test", "Test")
                        .WithMany("Attempts")
                        .HasForeignKey("Testid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attempts_tests_testid");

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Group", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_groups_courses_courseid");

                    b.HasOne("Unscriptable.Domain.Entitties.Direction", "Direction")
                        .WithMany("Groups")
                        .HasForeignKey("Directionid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_groups_directions_directionid");

                    b.HasOne("Unscriptable.Domain.Entitties.Project", "Project")
                        .WithMany("Groups")
                        .HasForeignKey("Projectid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_groups_projects_projectid");

                    b.Navigation("Course");

                    b.Navigation("Direction");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Question", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("Testid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_tests_testid");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Refreshtoken", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.User", "User")
                        .WithMany("Refreshtokens")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refreshtokens_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Student", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("Unscriptable.Domain.Entitties.Student", "Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_users_userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Testresult", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Attempt", "Attempt")
                        .WithMany("Testresults")
                        .HasForeignKey("Attemptid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_testresults_attempts_attemptid");

                    b.HasOne("Unscriptable.Domain.Entitties.Student", "Student")
                        .WithMany("Testresults")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_testresults_students_studentid");

                    b.HasOne("Unscriptable.Domain.Entitties.Test", "Test")
                        .WithMany("Testresults")
                        .HasForeignKey("Testid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_testresults_tests_testid");

                    b.Navigation("Attempt");

                    b.Navigation("Student");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Userattemptanswer", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Attempt", "Attempt")
                        .WithMany("Userattemptanswers")
                        .HasForeignKey("Attemptid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_userattemptanswers_attempts_attemptid");

                    b.HasOne("Unscriptable.Domain.Entitties.Question", "Question")
                        .WithMany("Userattemptanswers")
                        .HasForeignKey("Questionid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_userattemptanswers_questions_questionid");

                    b.Navigation("Attempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Userselectedoption", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Answer", "Answer")
                        .WithMany("Userselectedoptions")
                        .HasForeignKey("Answerid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_userselectedoptions_answers_answerid");

                    b.HasOne("Unscriptable.Domain.Entitties.Userattemptanswer", "Userattemptanswer")
                        .WithMany("Userselectedoptions")
                        .HasForeignKey("Userattemptanswerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_userselectedoptions_userattemptanswers_userattemptanswerid");

                    b.Navigation("Answer");

                    b.Navigation("Userattemptanswer");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Usertextanswer", b =>
                {
                    b.HasOne("Unscriptable.Domain.Entitties.Userattemptanswer", "Userattemptanswer")
                        .WithOne("Usertextanswer")
                        .HasForeignKey("Unscriptable.Domain.Entitties.Usertextanswer", "Userattemptanswerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usertextanswers_userattemptanswers_userattemptanswerid");

                    b.Navigation("Userattemptanswer");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Answer", b =>
                {
                    b.Navigation("Userselectedoptions");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Attempt", b =>
                {
                    b.Navigation("Testresults");

                    b.Navigation("Userattemptanswers");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Course", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Direction", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Project", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Userattemptanswers");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Student", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Testresults");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Test", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");

                    b.Navigation("Testresults");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.User", b =>
                {
                    b.Navigation("Refreshtokens");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Unscriptable.Domain.Entitties.Userattemptanswer", b =>
                {
                    b.Navigation("Userselectedoptions");

                    b.Navigation("Usertextanswer");
                });
#pragma warning restore 612, 618
        }
    }
}
